### PR TITLE
Add support to parse actorFor overload that accepts new Class<?>[]{... ...}

### PR DESCRIPTION
**Pull request by sharmapankaj2512**
- Add support to parse `actorFor` overload that accepts ` new Class<?>[]{... ...}`
- current implementation is fragile, in future it needs to be replaced with a better parser

### CODE REVIEW

**Comment by VaughnVernon** [comment]
@sharmapankaj2512 Thanks for the PR, but I don't see the failing test. AFAIK there is only the `CommandModelStoreProvider` in the place of the test.

**Comment by sharmapankaj2512** [comment]
> @sharmapankaj2512 Thanks for the PR, but I don't see the failing test. AFAIK there is only the `CommandModelStoreProvider` in the place of the test.

@VaughnVernon This file is just test data residing in the resources folder. It makes one of the existing test cases fail. Travis CI shows the failing test in ProtocolScanner. 

After you confirm that this is something that needs to fixed, I will replace the test data with a proper test case. I can also take a stab at fixing the issue.

**Comment by kmruiz** [comment]
Hi @sharmapankaj2512 , thanks for sharing!!

The test is here: https://github.com/vlingo/vlingo-build-plugins/blob/master/src/test/java/io/vlingo/maven/codegen/ProtocolScannerTest.java#L18

Test implementation is here: https://github.com/vlingo/vlingo-build-plugins/blob/master/src/main/java/io/vlingo/maven/codegen/ProtocolScanner.java

The issue is that the ProtocolScanner depends on having a single protocol in the actorFor. The implementation is here:

https://github.com/vlingo/vlingo-build-plugins/blob/master/src/main/java/io/vlingo/maven/codegen/ProtocolScanner.java#L84-L90

It seems that we need to add new logic to this method for the overloaded method actorFor.

**Review by VaughnVernon — APPROVED** [review]
@sharmapankaj2512 Awesome, thanks for your help!

**Pull request merged**
